VisorFolks/cyancore

src/arch/avr/8/5/terravisor/spinlock.S
src/include/compiler_macros.h
src/lib/libc/printf.c

<AVR8> Fixed context management in spinlock

---

mk/elf.mk
src/driver/build.mk
src/driver/driver.ld.sx
src/platform/mega_avr/atmega328p/include/plat_mem.h
src/platform/mega_avr/common/arch/platform_copy_data.S
src/platform/mega_avr/common/build.mk
src/platform/mega_avr/common/sections.ld.sx
src/sources.mk

* Add support for modularized linker scripts
* Updated sources to support the feature update
* Added size check in linker for compiletime safety

<Make> Updated build engine to support supplementary linker scripts

---

src/lib/libnmath/dsp/build.mk
src/lib/libnmath/dsp/conv.c
src/lib/libnmath/include/dsp.h
src/lib/libnmath/include/dsp/conv.h

---
* First commit for DSP support on Cyancore
* Added convolution function

<DSP> Adding support for DSP

---

src/driver/syslog/syslog.c
src/include/syslog/syslog.h
src/include/syslog/syslog_config.h

Addition of callbacks to syslog system.

Add callbacks to syslog.

---

src/include/compiler_macros.h
src/include/insignia.h
src/lib/libc/include/stdbool.h
src/projects/demo_avr_cpp/build.mk
src/projects/demo_avr_cpp/config.mk
src/projects/demo_avr_cpp/gpio.cpp
src/projects/demo_avr_cpp/gpio.h
src/projects/demo_avr_cpp/project.cpp

* Added cpp sources of project and gpio
* Updated compiler macros
* Fixed stdbool.h compilation error for cpp

<Demo_AVR> Adding cpp example of blinky on AVR

---

src/driver/console/console_membuf/console_membuf.c
src/platform/mega_avr/common/hal/uart/uart.c

Reverts VisorFolks/cyancore#57

Revert "(Console) Bug fix for membuf & Uart"

---

src/arch/avr/8/common_5x_6/terravisor/arch.c
src/arch/avr/8/common_5x_6/terravisor/include/arch.h
src/driver/console/console_serial/console_serial.c
src/platform/mega_avr/common/hal/gpio/gpio.c
src/platform/mega_avr/common/hal/uart/uart.c
src/platform/mega_avr/common/platform/platform_wdt.c

- Updated the call architecture to accept ret pointer
- return info will now be preset in mret struct

<AVR> Arch machine call bug fix

---

src/driver/console/console.c
src/driver/console/console_membuf/earlycon_membuf.c
src/driver/console/console_serial/console_serial.c
src/driver/console/console_serial/earlycon_serial.c
src/driver/interrupt/interrupt_controller.c
src/driver/interrupt/plic/plic.c
src/driver/interrupt/plic/plic_private.h
src/driver/watchdog/watchdog.c
src/include/driver/console.h
src/include/driver/interrupt_controller.h
src/include/driver/watchdog.h
src/platform/mega_avr/common/platform/platform_wdt.c

- Updated console, interrupt controller, watchdog
- Setup function call is now offloaded to driver setup function
- Added locks to avoid race conditions on multi core

<Drivers> Updated driver architecture

---

README.md
src/engine/banner.mk

- Updated version in banner
- Updated readme version

[Release #3] Updated banner and readme

---

mk/path.mk
mk/picotool.mk
mk/project.mk

- This patch support generation of picotool from sources
- Added new folder "misc_bins" for storing all misc binaries
used by CC
- Added new targets get_picotool, install_pt_dep, pt_clean

<RPi-Pico> Added picotool to build engine of CC

---

src/include/status.h
src/include/utils.h
src/lib/libc/include/stdlib.h
src/lib/libc/malloc_lite.c
src/lib/libc/printf.c
src/platform/mega_avr/atmega328p/include/plat_mem.h
src/platform/sifive/fe310g002/include/plat_mem.h

- Added irq save locks to support multi-core processing
and multi-threading
- Fixed free call and added boundary case checks

<heap> Add multi-core support and bug fixes

---

src/platform/mega_avr/common/arch/platform_copy_data.S
src/platform/mega_avr/common/include/platform.h
src/platform/mega_avr/common/platform/build.mk
src/platform/mega_avr/common/platform/platform.c
src/platform/sifive/common_fe310/include/platform.h
src/platform/sifive/common_fe310/platform/build.mk
src/platform/sifive/common_fe310/platform/platform.c

<MegaAVR> Fixed data copy routine

---

src/lib/libnmath/arithmetic/arithmetic.c
src/lib/libnmath/arithmetic/build.mk
src/lib/libnmath/include/cmath.h
src/lib/libnmath/include/nmath.h

* Arithmetic
- isPrime
* Complex Math
- new datatypes
Issue #173

<NMath> Add new functions to libnmath

---

src/visor/terravisor/services/kernel/cc_os_sched.c
src/visor/terravisor/services/kernel/cc_os_sem.c

<CC_OS> #186 Bug Fixed

---

src/platform/mega_avr/atmega2560/config.mk
src/platform/mega_avr/atmega2560/include/plat_mem.h
src/platform/mega_avr/atmega328p/config.mk
src/platform/mega_avr/atmega328p/include/plat_mem.h
src/platform/sifive/fe310g002-bl/config.mk
src/platform/sifive/fe310g002-bl/include/plat_mem.h
src/platform/sifive/fe310g002/config.mk
src/platform/sifive/fe310g002/include/plat_mem.h

- Now add [HEAP/STACK]_SIZE in project/<name>/config.mk
eg: `HEAP_SIZE := 1024`
Issue: #192

<Make> Moved heap and stack size spec to config.mk

---

src/lib/libc/scanf.c

<libc> getchar bugfix

---

src/include/visor/terravisor/cc_os/cc_os_tasks.h
src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
src/visor/terravisor/services/kernel/cc_os_task_idle.c
src/visor/terravisor/services/kernel/cc_os_tasks.c

Signed-off-by: panjalchanda08 <pranjalchanda08@gmail.com>
Closes #206

<CC_OS> Add functional callback hook for users

---

mk/lint.mk
projects/demo_avr_cpp/project.cpp
src/arch/avr/8/common_5x_6/terravisor/arch.c
src/arch/avr/8/common_5x_6/terravisor/include/arch.h
src/driver/driver.c
src/lib/libc/malloc_lite.c
src/lib/libnmath/dsp/conv.c
src/lib/libnmath/include/dsp/conv.h
src/platform/mega_avr/common/platform/platform_timer.c
src/platform/sifive/common_fe310/hal/prci/pll.c
src/visor/terravisor/workers/mcall/machine_call.c

<Lint> Updated cppcheck flags and fixed code smells

---

src/arch/avr/8/common_5x_6/terravisor/arch.c
src/arch/avr/8/common_5x_6/terravisor/asm.S
src/arch/avr/8/common_5x_6/terravisor/include/avr.h

<AVR8> Updated ctx mgnt frame to reduce stk use

---

src/include/visor/terravisor/cc_os/cc_os_tasks.h
src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
src/visor/terravisor/services/kernel/cc_os_tasks.c

<CC_OS> Add task ID

---

mk/picotool.mk
mk/qemu.mk

<Make> Fix for failure of build resume and updates

---

src/arch/avr/8/common_5x_6/terravisor/asm.S

<AVR8> SP computation fixed in ISR

---

src/arch/riscv/32/i/terravisor/entry.S

<RV32I> Fix stack compute for MP Core

---

src/include/status.h
src/include/visor/terravisor/helios/helios.h
src/include/visor/terravisor/helios/helios_mutex.h
src/include/visor/terravisor/helios/utils/helios_sched.h
src/visor/terravisor/services/kernel/helios_mutex.c
src/visor/terravisor/services/kernel/helios_sem.c

Issue: #184
Signed-off-by: Dybios <dibyajyoti.samal@gmail.com>

<HELIOS> Add mutex support

---

mk/qemu.mk

- Updated qemu uninstallation routines to clean up the environment.
Bug Issue: Resolves #247

<Make> Updated clean_qemu routines

---

README.md

Update in readme about project details and image resize update.

Shubhangi47 patch 1_ Readme update

---

src/arch/riscv/32/i/terravisor/entry.S

<RV32I> Fixed the order of assembler directives

---

.vscode/settings.json
src/arch/avr/8/common_5x_6/terravisor/arch.c
src/arch/avr/8/common_5x_6/terravisor/include/arch.h
src/arch/avr/8/common_5x_6/terravisor/init.c
src/platform/mega_avr/common/platform/platform.c

added support for unique random number generation for a common AVR platform.

Added support for unique random number generation for avr platform

---

src/lib/libc/include/stdlib.h
src/lib/libc/strton.c

Added implementations for atoi, atol & atof functions.
Issue: #262

Feature/sagarladla/262 <lib c> add functions in stdlib

---

projects/demo_ibex_ss/project.c
src/platform/ibex/simple_system/platform/platform.c

- Updated project to keep it minimal
- Tests all the simple-system devices

<ibex> Add support for exiting simulation

---

src/arch/riscv/32/i/terravisor/exception_handler.c

[RV32I] bug fix for exception handler

---

mk/qemu.mk

- Added support for aarch64-softmmu, riscv64-softmmu and x86_64-softmmu targets
- Using latest stable release
Issue: #310

<qemu> Now using QEMU v9.0.0 release

---

src/platform/sifive/qemu-sifive-e/resources/dp.c

<QEMU-SiFive-E> Updated RTC Clock
